### ISSUE TITLE
Earth Shard

### ISSUE THREAD

**Issue by jchilleo** [jedk1/JedCoreDownload#2]
Using your newest .jar earth shard damage can't be modified.

When I change earth shards damage output to be stronger it doesn't do anything in game. I have stronger mobs in my game so I need to adjust my the strength of the abilities. I hope this is just a bug and not a forced damaged amount. 

If you need more information let me know.

edit: never mind I am stupid I just needed to delete my config and redo it to fix it.

**Comment by jedk1** [comment]
no worries
