### ISSUE TITLE
Metal Hook Stuck

### ISSUE THREAD

**Issue by jchilleo** [jedk1/JedCoreDownload#3]
For starters there is no errors produced to the log.

But Metal hook seems to be a bit wonky. There is often times people are reporting the hook will not pull them, in addition to being stuck on a wall for longer than usual times. Not sure if this is a known issue, but if you need more information let me know.

**Comment by jedk1** [comment]
Metal hook has always been weird. I don't really have the time to fix it though sorry. Also a lot of the bugs with it are caused by the players having ping worse than 0.
