### ISSUE TITLE
Update Required

### ISSUE THREAD

**Issue by Rektmeneer** [jedk1/JedCoreDownload#7]
Hello Maker of JedCore,

I think you are already working on it but i still wanted to say it. JedCore needs a update to be compatible with 1.8.4 becouse there are some cool updates/changes to PK and i really want to update to 1.8.4 but i still want Jedcore becouse its so important for my server. So please update it!

Thank you for reading!

**Comment by jedk1** [comment]
Please go through my repos and find the Jedcore repo. I honestly dont care about jedcore or bending anymore. It got boring. Im not updating.
