### ISSUE TITLE
ProjectKorra 1.8.4 [Update]

### ISSUE THREAD

**Issue by Ji-Rath** [jedk1/JedCoreDownload#9]
As of the latest PK update, the plugin appears to stop working. 
It shows this error while trying earth moves such as EarthLine: https://pastebin.com/kRe0exFe
While for other elements such as fire, the ability states when you try to bind it: " 'ability' cannot be bound!"

A hopefully quick patch would be very appreciated. If you need any help with finding more bugs, feel free to message me.

**Comment by jedk1** [comment]
Read the previous errors on this and on the JedCore repo.
